# Generated by Django 4.0.4 on 2022-05-12 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_alter_discussioncomment_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='createddate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
