# Generated by Django 4.0.4 on 2022-05-12 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_discussion_createddate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ['-createddate']},
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='created_date',
        ),
    ]
