# Generated by Django 4.0.4 on 2022-05-12 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0004_alter_discussion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='createddate',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
