# Generated by Django 4.0.4 on 2022-05-16 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussion', '0006_alter_discussioncomment_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyDiscussionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('discussion_reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_comments', to='discussion.discussioncomment')),
            ],
        ),
        migrations.CreateModel(
            name='LikeDisComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='discussion.discussioncomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
