# Generated by Django 4.0.4 on 2022-06-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdiscussion',
            name='reason',
            field=models.CharField(choices=[("It's spam", "It's spam"), ('Hate speech or symbols', 'Hate speech or symbols'), ('Bullying or harassement', 'Bullying or harassement'), ('Nudity or sexual activity', 'Nudity or sexual activity')], default="It's spam", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportdiscussion',
            name='text',
            field=models.TextField(default=('Hate speech or symbols', 'Hate speech or symbols')),
            preserve_default=False,
        ),
    ]
