# Generated by Django 4.0.4 on 2022-06-09 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0010_reportdiscussion_reason_reportdiscussion_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
