# Generated by Django 4.0.4 on 2022-06-09 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0012_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
