# Generated by Django 4.0.4 on 2022-06-09 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0014_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
