# Generated by Django 4.0.4 on 2022-05-04 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_addcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='addComment',
        ),
        migrations.DeleteModel(
            name='EventModel',
        ),
    ]
