# Generated by Django 4.0.4 on 2022-05-08 05:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='joiners',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_joining', to=settings.AUTH_USER_MODEL),
        ),
    ]
