# Generated by Django 4.0.4 on 2022-05-10 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='enddate_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='startdate_time',
        ),
    ]
