# Generated by Django 4.0.4 on 2022-05-11 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_event_end_date_event_end_time_event_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='joiners',
        ),
    ]
