# Generated by Django 4.0.4 on 2022-05-31 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_reportevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportEvent',
        ),
    ]
