# Generated by Django 4.0.4 on 2022-05-31 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0015_delete_reportevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[("It's spam", "It's spam"), ('Hate speech or symbols', 'Hate speech or symbols'), ('Bullying or harassement', 'Bullying or harassement'), ('Nudity or sexual activity', 'Nudity or sexual activity')], max_length=150)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_by', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
    ]
