# Generated by Django 4.0.4 on 2022-05-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner_pic',
            field=models.ImageField(blank=True, null=True, upload_to='banner_pic'),
        ),
    ]
