# Generated by Django 4.0.4 on 2022-05-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_banner_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularDest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('pop_image', models.ImageField(blank=True, null=True, upload_to='pop_images')),
            ],
        ),
    ]
