# Generated by Django 4.0.4 on 2022-06-01 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_reportuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportuser',
            name='text',
            field=models.TextField(default='2022-05-30'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendhostrequest',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
