# Generated by Django 4.0.4 on 2022-06-03 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_sendhostrequestreply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockUser',
        ),
    ]
