# Generated by Django 4.0.4 on 2022-06-08 06:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_album_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
